version: '3.3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_connect
      - POSTGRES_USER=test_connect
      - POSTGRES_PASSWORD=test_connect
      - MAX_CONNECTIONS=300